---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-counter-deployment
spec:
  template:
    metadata:
      labels:
        app: twitter-counter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7071"
    spec:
      containers:
      - name: twitter-counter
        image: maxwo/twitter-counter:0.1.0-SNAPSHOT
        livenessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: tweet-counter
  labels:
    app: tweet-counter-1
spec:
  ports:
  - name: client
    port: 8080
    protocol: TCP
  selector:
    app: twitter-counter
