---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7071"
    spec:
      containers:
      - name: zookeeper-member
        image: maxwo/zookeeper:3.4.10

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  selector:
    app: zookeeper
