---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: maxwo/grafana:4.6.3-1
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana-1
spec:
  ports:
  - name: client
    port: 3000
    protocol: TCP
  selector:
    app: grafana


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: grafana-ui
 annotations:
   kubernetes.io/ingress.class: traefik
spec:
 rules:
 - host: "grafana.zenikube.local"
   http:
     paths:
     - backend:
         serviceName: grafana
         servicePort: 3000
